---
# Display the first 12 lines of the /usr/bin/clean-binary-files file and
# send theoutput to the /home/student/headtail.txt file.
- name: head
  shell: |
    head -n 12 /usr/bin/clean-binary-files > /home/student/headtail.txt

# Display the last nine lines of the /usr/bin/clean-binary-files file and
# add theoutput to the /home/student/headtail.txt file.
- name: tail
  shell: |
    tail -n 9 /usr/bin/clean-binary-files >> /home/student/headtail.txt
