---
# Create a new static network connection
# IPv4 172.25.x.11/16
# IPv4 10.0.11.1/24
# gw 172.25.0.1
# dns 172.25.254.254
# Configure the new connection to be automatically started.
- name: review eth0
  nmcli:
    state: present
    conn_name: review
    ifname: eth0
    type: ethernet
    ip4: 172.25.11.11/16, 10.0.11.1/24
    gw4: 172.25.0.1
    dns4: 172.25.254.254
    autoconnect: true

# Other connections should not start automatically.
- name: only eth0 start on boot
  nmcli:
    state: present
    conn_name: System eth0
    autoconnect: false

# Configure the hosts file so that 10.0.X.1 can be referenced as "myhost"
- name: setup of /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "10.0.11.1 myhost"

# Set the host name to serverX.example.com
- name: hostname change
  hostname:
    name: server11.example.com
